# -*- coding: utf-8 -*-
"""Eclat_AssociationLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrbeZLSqFW_Fh2kvyzDY7v7DMrzIBElF

# **Eclat Association Rule Learning Model**

## **Installing Apyori**
"""

!pip install apyori

"""## **Importing Library**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## **Data Preprocessing**"""

dataset= pd.read_csv('Market_Basket_Optimisation.csv',header=None)
transactions = []
for i in range (0,7501):
  transactions.append([str(dataset.values[i,j]) for j in range (0,20)])

"""## **Training the Eclat Model**"""

from apyori import apriori
rules = apriori(transactions=transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2,max_length=2)

"""## **Visualising The Result**

## **Displaying the first results coming directly from the output of the apriori function**
"""

results=list(rules)
results

"""## **Putting the results well organised into a Pandas DataFrame**"""

def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]

    return list(zip(lhs, rhs, supports))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Product Bought', 'Product Likely To Buy', 'Support'])

"""## **Displaying the results non sorted**"""

resultsinDataFrame

"""## **Displaying the results sorted by descending Support**"""

resultsinDataFrame.nlargest(n = 10, columns = 'Support')